name: Docker Image CI

on:
  workflow_run:
    workflows: ["docker-image"]
    types: 
    - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Docker Pull Image
      run: docker pull naveen7k/my-webapp:latest
    - name: Run docker container
      run: docker run -d -p 8082:8082 --name my-webapp-container naveen7k/my-webapp:latest
